<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>transferStatusCLICK</name>
   <tag></tag>
   <elementGuidId>1eb6cd40-a042-4195-8463-56b6af80c486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='transferStatus']/../../td[2]/div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='transferStatus']/../../td[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='transferStatus']/../../td[2]/div</value>
   </webElementProperties>
</WebElementEntity>
