<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SuiteGhibli</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-02-14T17:42:33</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>07b583ce-ec97-4d21-ae4c-a4b65ca5a5ef</testSuiteGuid>
   <testCaseLink>
      <guid>b20d1f43-988c-4d48-94f0-2ea12ef9a026</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a137b6df-1680-4dbf-823a-3a15cd3a1231</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de60f2bf-8869-4f2a-a95f-e9ad07d8a886</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c13e1b8-80e2-4f3e-bedb-6ca89950774f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a92a79c-07bd-446d-8e1f-6c5bf503fe92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d8782c73-2584-4322-b31f-67a3a1d4e21d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DashboardTransportFilter</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
